config/routes.rb
Scheduler::Application.routes.draw do

  devise_for :users

  get 'schedules/month' => 'schedules#month', :as => 'month_schedules'
  get 'schedules/view_file' => 'schedules#view_file', :as => 'view_file_schedules'
  post 'schedules/search' => 'schedules#search', :as => 'search_schedules'
	get 'schedules/show' => 'schedules#show', :as => 'show_schedules'

	get 'account/list_group' => 'account#list_group', :as => 'account_list_group'
	get 'account/edit_group' => 'account#edit_group', :as => 'account_edit_group'
	get 'account/destroy_group' => 'account#destroy_group', :as => 'account_destroy_group'
	get 'account/new_group'=> 'account#new_group', :as => 'account_new_group'
	post 'account/create_group'=> 'account#create_group', :as => 'account_create_group'
	post 'account/update_group'=> 'account#update_group', :as => 'account_update_group'
  get 'account/list_member' => 'account#list_member', :as => 'account_list_member'
  get 'account/new_member' => 'account#new_member', :as => 'account_new_member'
  get 'account/edit_member' => 'account#edit_member', :as => 'account_edit_member'
	post 'account/create_member'=> 'account#create_member', :as => 'account_create_member'
	post 'account/update_member'=> 'account#update_member', :as => 'account_update_member'
	get 'account/destroy_member' => 'account#destroy_member', :as => 'account_destroy_member'
  
  resources :schedules

   root :to => "schedules#month"

end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id         :integer          not null, primary key
#  datetime   :datetime
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#  file_name  :string(255)
#  user_id    :integer
#  group_id   :integer
#

class Schedule < ActiveRecord::Base
  validates_presence_of :title
	paginates_per 3
	belongs_to(:user)
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

	before_filter :authenticate_user!, :except=>[ :month ]

#	FILE_PATH = "#{Rails.root.to_s}/files/#{ENV['RAILS_ENV']}"
	FILE_PATH = "#{Rails.root.to_s}/public"
  # GET /schedules
  # GET /schedules.xml

  def index

			@schedules = Schedule.where('user_id = ? or group_id = ?', current_user[:id], current_user[:group_id] ).
														order('datetime DESC').page(params[:page]).per(5)

# render :text => "#{Schedule.class}" #for debug


#    respond_to do |format|
#      format.html # index.html.erb
#      format.json  { render :json => @schedules }
#    end
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
		@schedule = Schedule.find(params[:id])
		@all = Schedule.find(:all, :order => 'datetime DESC')
#   respond_to do |format|
#   format.html # show.html.erb
#   format.xml  { render :xml => @schedule }
#   end
  end

  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    @schedule = Schedule.new
      if params[:date]
        @schedule.datetime = Time.parse(params[:date]) rescue nil
      end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    find_schedule
  end

  # POST /schedules
  # POST /schedules.xml
  def create
		set_file_name
    @schedule = Schedule.new(params[:schedule])
		@schedule[:group_id] = current_user.group_id
		@schedule[:user_id] = current_user.id
    respond_to do |format|
      if @schedule.save
				save_file
        format.html { redirect_to(@schedule, :notice => 'Schedule was successfully created.') }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.xml
  def update
		set_file_name
    find_schedule

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
				save_file
        format.html { redirect_to(@schedule, :notice => 'Schedule was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.xml
  def destroy
    find_schedule
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to(schedules_url) }
      format.xml  { head :ok }
    end
  end
  
  def month
    @year = params[:year] ? params[:year].to_i : Time.now.year
#render :text => "#{@month_next}" #デバック用
    @month = params[:month] ? params[:month].to_i : Time.now.month
    unless Date.valid_date?(@year, @month, 1)
      @year = Time.now.year
      @month = Time.now.month
    end
    @this = DateTime.new(@year, @month, 1, 0, 0, 0, '+09:00')
#render :text => "#{@this}"
    @prev = (@this << 1)
    @next = (@this >> 1)
    @schedules = Hash.new{|hash, key| hash[key] = []}
		if current_user
#	    Schedule.where('user_id = ? or group_id = ?', current_user[:id], current_user[:group_id] ).find(:all, :conditions => ['datetime >= ? And datetime < ? ',@this, @next]).each do |schedule|

			Schedule.where('user_id = ? or group_id = ?', current_user[:id], current_user[:group_id] ).find(:all).each do |schedule|
#render :text => "#{@this}"
#break
				if schedule.datetime.to_datetime >= @this  and schedule.datetime.to_datetime < @next
	      	date = Date.new(schedule.datetime.year,
                      schedule.datetime.month,
                      schedule.datetime.day)
	      	@schedules[date] << schedule
				end
			end
		end
  end
  
	def view_file
		find_schedule
		file = "#{FILE_PATH}/#{@schedule.id}"
		send_file(file, :filename => @schedule.file_name, :stream => false, :disposition => 'inline')
	end

	def search
		schedules = Schedule.find(:all,
															#:include => [:user],
															#:conditions => ['users.group_id = ?', session[:user].group_id],
															:order => 'datetime DESC')
		regexp = Regexp.new(params[:schedule][:title], true)
		@results = schedules.select do |schedule|
			regexp =~ schedule.title || regexp =~ schedule.content
		end
		if @results.empty?
#			redirect_to (:month_schedules, :notice => '見つかりません。')
			render(:partial => 'not_found')
		else
#			redirect_to :action => 'show',:id => @results
			render(:partial => 'found')
		end
	end

	private

	def find_schedule
		@schedule = Schedule.find(params[:id])
	end

	def set_file_name
		@file = params[:schedule][:file_name]
		params[:schedule][:file_name] = @file.original_filename if @file
	end

	def save_file
		if @file
			File.open("#{FILE_PATH}/#{@schedule.id}", "wb") do |f|
				f.write(@file.read)
			end
		end
	end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  include CalendarHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule, :html => {:multipart => true}) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :datetime %><br />
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :cols => 40, :rows => 10 %>
  </div>
	<div class="field">
    <%= f.label :file_name %><br />
				<%= link_to(@schedule.file_name, view_file_schedules_path(:id => @schedule)) if @schedule.file_name %>
    <%= f.file_field :file_name %>
  </div>
  <div class="actions">
    <%= f.submit('作成・更新') %>
  </div>
<% end %>

app/views/schedules/_found.html.erb
<dl>
	<% for schedule in @results -%>
	<dt><%= format_datetime(schedule.datetime) %></dt>
	<dd><%= link_to(schedule.title, :action => 'show', :id => schedule) %></dd>
	<% end %>
</dl>

app/views/schedules/_found.js.erb
$("#results").html('<dl><% for schedule in @results -%><dt><%= format_datetime(schedule.datetime) %></dt><dd><%= link_to(schedule.title, :action => 'show', :id => schedule) %></dd><% end %></dl>')

app/views/schedules/_not_found.html.erb
見つかりませんでした。

app/views/schedules/_not_found.js.erb
$("#results").html("見つかりませんでした。")

app/views/schedules/edit.html.erb
<h1>スケジュールの編集</h1>

<%= render 'form' %>

<%= link_to '見る', @schedule %> |
<%= link_to 'カレンダーへ戻る',	:action => 'month', :year => @schedule.datetime.year, :month => @schedule.datetime.month %>
<%= link_to('スケジュール一覧', :action => 'index' )%>

app/views/schedules/index.html.erb
<h1>スケジュール一覧</h1>

<table >
  <tr>
    <th>Datetime</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
		<% if user_signed_in? %>
    <th></th>
    <th></th>
		<% end %>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.datetime.strftime("%Y年 %m月 %d日 %p %I時 %M分 ") %></td>
    <td><%= schedule.title %></td>
    <td><%= linebreaksbr(schedule.content).html_safe %></td>
    <td><%= link_to '詳細', schedule %></td>
		<% if user_signed_in? %>
    <td><%= link_to '編集', edit_schedule_path(schedule) %></td>
    <td><%= link_to '削除', schedule, :confirm => 'Are you sure?', :method => :delete %></td>
		<% end %>
  </tr>
<% end %>
</table>

<br />

<% if user_signed_in? %>
<%= link_to '新規スケジュール追加', new_schedule_path %>
<% end %>
<%= paginate @schedules %>

app/views/schedules/month.html.erb
<div id = pagebody>
<h1>月間スケジュール　<%= @this.strftime('%Y年%m月')%></h1>

<% if current_user %>
<p><%= "#{current_user[:email]}さんがログインしています。"%></p>
<% else %>
<p><%= "ログイン、またはユーザー登録してください。"%></p>
<% end %>

<hr />
<div>
	<% if user_signed_in? %>
	<%= link_to('スケジュールを新規追加', new_schedule_path) %>
	<% end %>
	<%= link_to('スケジュール一覧', :action => 'index')%>
</div>

<div>
	<%= link_to('前へ', :action => 'month', :year => @prev.year, :month => @prev.month )%>
	<%= link_to('今月', :action => 'month')%>
	<%= link_to('次へ', :action => 'month', :year => @next.year, :month => @next.month )%>
</div>
<br />

<div id = this_and_prev>
<div id = prev_month>
	<%= calendar(:year => @year, :month => @prev.month) do |date|
		cell_text = link_to(date.mday.to_s, :action => 'new', :date => date)
		cell_attrs = {:class => 'day'}
		@schedules[date].each do |schedule|
			cell_attrs[:class] = 'specialDay'
			cell_text << "<br />\n".html_safe
			cell_text << link_to(h(schedule.title), :action => 'show', :id => schedule)
		end

		[cell_text, cell_attrs]
	end.html_safe
	%>
</div>

<div id = this_month>
	<%= calendar(:year => @year, :month => @month) do |date|
		cell_text = link_to(date.mday.to_s, :action => 'new', :date => date)
		cell_attrs = {:class => 'day'}
		@schedules[date].each do |schedule|
			cell_attrs[:class] = 'specialDay'
			cell_text << "<br />\n".html_safe
			cell_text << link_to(h(schedule.title), :action => 'show', :id => schedule)
		end

		[cell_text, cell_attrs]
	end.html_safe
	%>
</div>
</div>

<div id = next_month>
	<%= calendar(:year => @year, :month => @next.month) do |date|
		cell_text = link_to(date.mday.to_s, :action => 'new', :date => date)
		cell_attrs = {:class => 'day'}
		@schedules[date].each do |schedule|
			cell_attrs[:class] = 'specialDay'
			cell_text << "<br />\n".html_safe
			cell_text << link_to(h(schedule.title), :action => 'show', :id => schedule)
		end

		[cell_text, cell_attrs]
	end.html_safe
	%>
</div>

<div id = footer>
<%= form_for(:schedule, :url => { :action => "search" }, :remote => true ) do |f| %>
	<p>
		<%= f.text_field(:title) %>
		<%= f.submit("検索") %>
	</p>
<% end %>
</div>

<div id = "results">
</div>

</div>

app/views/schedules/new.html.erb
<h1>新規スケジュール</h1>

<%= render 'form' %>

<%= link_to 'カレンダーへ', :action => 'month' %>
<%# link_to('スケジュール一覧', :action => 'index')%>

app/views/schedules/show.html.erb
<h1>スケジュール詳細</h1>
<hr />

<div>
	<p>タイトル</p>
	<p><%= h(@schedule.title) %></p>
	<dt>日付</dt>
	<p><%= format_datetime(@schedule.datetime) %></p>
	<p>内容</p>
	<p><%= linebreaksbr(@schedule.content).html_safe %></p>
	<% if @schedule.attribute_present?('file_name') %>
	<p>添付ファイル<pt>
		<%= link_to(@schedule.file_name, view_file_schedules_path(:id => @schedule)) if @schedule.file_name %>
	</dd>
	<% end %>
</div>

<% if user_signed_in? %>
<%= link_to '編集', edit_schedule_path(@schedule) %><% end %> 
<%= link_to 'カレンダーヘ戻る',	:action => 'month', :year => @schedule.datetime.year, 
										:month => @schedule.datetime.month %>
<% @all.each_with_index do |e,index|
		if e.eql?@schedule %>
				<%= link_to('スケジュール一覧へ戻る', :action => 'index', :page => index/5 )%>
		<% end %>
<% end %>