config/routes.rb
Scheduler::Application.routes.draw do

  devise_for :users

  get 'schedules/month' => 'schedules#month', :as => 'month_schedules'
  get 'schedules/view_file' => 'schedules#view_file', :as => 'view_file_schedules'
  post 'schedules/search' => 'schedules#search', :as => 'search_schedules'
	get 'schedules/show' => 'schedules#show', :as => 'show_schedules'

	get 'account/list_group' => 'account#list_group', :as => 'account_list_group'
	get 'account/edit_group' => 'account#edit_group', :as => 'account_edit_group'
	get 'account/destroy_group' => 'account#destroy_group', :as => 'account_destroy_group'
	get 'account/new_group'=> 'account#new_group', :as => 'account_new_group'
	post 'account/create_group'=> 'account#create_group', :as => 'account_create_group'
	post 'account/update_group'=> 'account#update_group', :as => 'account_update_group'
  get 'account/list_member' => 'account#list_member', :as => 'account_list_member'
  get 'account/new_member' => 'account#new_member', :as => 'account_new_member'
  get 'account/edit_member' => 'account#edit_member', :as => 'account_edit_member'
	post 'account/create_member'=> 'account#create_member', :as => 'account_create_member'
	post 'account/update_member'=> 'account#update_member', :as => 'account_update_member'
	get 'account/destroy_member' => 'account#destroy_member', :as => 'account_destroy_member'
  
  resources :schedules

   root :to => "schedules#month"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>みんなのスケジューラー<%= controller.action_name %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<p style="color: green" class="notice"><%= notice %></p>
<p style="color: red" class="alert"><%= alert %></p>

<%= yield %>

<hr />

<div style = "text-align: left;">
	<%= link_to_unless_current('カレンダー', month_schedules_path) %> |
	<%= link_to_unless_current('ユーザー管理', account_list_group_path) %> |
	<% if user_signed_in? %>
		<%= link_to "ログアウト", destroy_user_session_path %>
	<% else %>
		<%= link_to "ログイン", new_user_session_path %> |
		<%= link_to 'ユーザー登録', [ :new, :user_registration ]  %>
	<% end %>
	<p><%#= link_to 'パスワード再発行', [ :new, :user_password ]  %></p>
	<p><%#= link_to '登録確認メール再送信', [ :new, :user_confirmation ]  %></p>
</div>

<div style = "text-align: right;">
	Powered by <a href="http://www.ruby-lang.org/">Ruby</a>
	and
	<a href="http://www.rubyonrails.org/">Ruby on rails</a>
</div>
</body>
</html>